export interface IProduct {
  id?: string;
  name: string;
  category: string;
  subCategory?: string | null;
  images: string[];
  colours: string[];
  fabricDetails: string;
  quantity: number;
  fullPrice: number;
  discountPrice: number;
  isBestSeller: boolean;
  isWholesale: boolean;
  isBlocked: boolean;
  seoTitle?: string | null;
  metaDescription?: string | null;
  description?: string | null;
  sku?: string;
  slug?: string;
  pattern?: string;
  fabric?: string;
  careInstructions?: string;
  fabricQuality?: string;
  kameezLength?: string;
  shalwarLength?: string;
  dupattaLength?: string;
  discountPercentage?: string;
  stockStatus?: string;
  altText?: string;
  tags?: string[];
  minWholesaleQuantity?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface CreateProductDTO {
  name: string;
  category: string;
  subCategory?: string;
  images: string[];
  colours: string[];
  fabricDetails: string;
  quantity: number;
  fullPrice: number;
  discountPrice: number;
  isBestSeller?: boolean;
  isWholesale?: boolean;
  seoTitle?: string;
  metaDescription?: string;
  description?: string;
  sku?: string;
  slug?: string;
  pattern?: string;
  fabric?: string;
  careInstructions?: string;
  fabricQuality?: string;
  kameezLength?: string;
  shalwarLength?: string;
  dupattaLength?: string;
  discountPercentage?: string;
  stockStatus?: string;
  altText?: string;
  tags?: string[];
  minWholesaleQuantity?: number;
}

export interface UpdateProductDTO {
  name?: string;
  category?: string;
  subCategory?: string;
  images?: string[];
  colours?: string[];
  fabricDetails?: string;
  quantity?: number;
  fullPrice?: number;
  discountPrice?: number;
  isBestSeller?: boolean;
  isWholesale?: boolean;
  isBlocked?: boolean;
  seoTitle?: string;
  metaDescription?: string;
  description?: string;
  sku?: string;
  slug?: string;
  pattern?: string;
  fabric?: string;
  careInstructions?: string;
  fabricQuality?: string;
  kameezLength?: string;
  shalwarLength?: string;
  dupattaLength?: string;
  discountPercentage?: string;
  stockStatus?: string;
  altText?: string;
  tags?: string[];
  minWholesaleQuantity?: number;
}
